[workspace]
members = [
  "crates/*",
  "tests",
]
resolver = "2"

[workspace.dependencies]
hdi = "0.2.3"
hdk = "0.1.3"
serde = "1"
holochain = "0.1.5"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
